package com.babcsany.minecraft.ervin_mod_1.init.block.animation.colors;

import com.babcsany.minecraft.ervin_mod_1.Ervin_mod_1;
import com.babcsany.minecraft.ervin_mod_1.init.sound.SoundInit;
import net.minecraft.block.AbstractBlock;
import net.minecraft.block.Block;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class BlockItemInit {

    public static final DeferredRegister<Block> ANIMATION_BLOCKS = DeferredRegister.create(ForgeRegistries.BLOCKS, Ervin_mod_1.MOD_ID);

    public static final RegistryObject<Block> animation_0 = ANIMATION_BLOCKS.register("animation/colors/1/255/0", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_1 = ANIMATION_BLOCKS.register("animation/colors/1/255/1", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_2 = ANIMATION_BLOCKS.register("animation/colors/1/255/2", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_3 = ANIMATION_BLOCKS.register("animation/colors/1/255/3", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_4 = ANIMATION_BLOCKS.register("animation/colors/1/255/4", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_5 = ANIMATION_BLOCKS.register("animation/colors/1/255/5", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_6 = ANIMATION_BLOCKS.register("animation/colors/1/255/6", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_7 = ANIMATION_BLOCKS.register("animation/colors/1/255/7", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_8 = ANIMATION_BLOCKS.register("animation/colors/1/255/8", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_9 = ANIMATION_BLOCKS.register("animation/colors/1/255/9", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_10 = ANIMATION_BLOCKS.register("animation/colors/1/255/10", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_11 = ANIMATION_BLOCKS.register("animation/colors/1/255/11", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_12 = ANIMATION_BLOCKS.register("animation/colors/1/255/12", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_13 = ANIMATION_BLOCKS.register("animation/colors/1/255/13", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_14 = ANIMATION_BLOCKS.register("animation/colors/1/255/14", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_15 = ANIMATION_BLOCKS.register("animation/colors/1/255/15", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_16 = ANIMATION_BLOCKS.register("animation/colors/1/255/16", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_17 = ANIMATION_BLOCKS.register("animation/colors/1/255/17", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_18 = ANIMATION_BLOCKS.register("animation/colors/1/255/18", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_19 = ANIMATION_BLOCKS.register("animation/colors/1/255/19", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_20 = ANIMATION_BLOCKS.register("animation/colors/1/255/20", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_21 = ANIMATION_BLOCKS.register("animation/colors/1/255/21", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_22 = ANIMATION_BLOCKS.register("animation/colors/1/255/22", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_23 = ANIMATION_BLOCKS.register("animation/colors/1/255/23", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_24 = ANIMATION_BLOCKS.register("animation/colors/1/255/24", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_25 = ANIMATION_BLOCKS.register("animation/colors/1/255/25", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_26 = ANIMATION_BLOCKS.register("animation/colors/1/255/26", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_27 = ANIMATION_BLOCKS.register("animation/colors/1/255/27", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_28 = ANIMATION_BLOCKS.register("animation/colors/1/255/28", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_29 = ANIMATION_BLOCKS.register("animation/colors/1/255/29", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_30 = ANIMATION_BLOCKS.register("animation/colors/1/255/30", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_31 = ANIMATION_BLOCKS.register("animation/colors/1/255/31", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_32 = ANIMATION_BLOCKS.register("animation/colors/1/255/32", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_33 = ANIMATION_BLOCKS.register("animation/colors/1/255/33", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_34 = ANIMATION_BLOCKS.register("animation/colors/1/255/34", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_35 = ANIMATION_BLOCKS.register("animation/colors/1/255/35", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_36 = ANIMATION_BLOCKS.register("animation/colors/1/255/36", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_37 = ANIMATION_BLOCKS.register("animation/colors/1/255/37", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_38 = ANIMATION_BLOCKS.register("animation/colors/1/255/38", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_39 = ANIMATION_BLOCKS.register("animation/colors/1/255/39", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_40 = ANIMATION_BLOCKS.register("animation/colors/1/255/40", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_41 = ANIMATION_BLOCKS.register("animation/colors/1/255/41", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_42 = ANIMATION_BLOCKS.register("animation/colors/1/255/42", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_43 = ANIMATION_BLOCKS.register("animation/colors/1/255/43", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_44 = ANIMATION_BLOCKS.register("animation/colors/1/255/44", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_45 = ANIMATION_BLOCKS.register("animation/colors/1/255/45", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_46 = ANIMATION_BLOCKS.register("animation/colors/1/255/46", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_47 = ANIMATION_BLOCKS.register("animation/colors/1/255/47", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_48 = ANIMATION_BLOCKS.register("animation/colors/1/255/48", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_49 = ANIMATION_BLOCKS.register("animation/colors/1/255/49", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
    public static final RegistryObject<Block> animation_50 = ANIMATION_BLOCKS.register("animation/colors/1/255/50", () -> new Block(AbstractBlock.Properties.create(Material.ROCK, MaterialColor.SNOW).setRequiresTool().speedFactor(4).hardnessAndResistance(5000000000000000000000000.0F).setLightLevel(Value -> 3).sound(SoundInit.AMBIENT_BASALT_NETHER_ADDITIONS)));
}
