package com.babcsany.minecraft.ervin_mod_1.init.item.food.brefk;

import com.babcsany.minecraft.ervin_mod_1.Ervin_mod_1;
import com.babcsany.minecraft.ervin_mod_1.item.brefk.*;
import com.babcsany.minecraft.ervin_mod_1.item.food.Foods;
import com.babcsany.minecraft.ervin_mod_1.item.group.ItemGroup;
import net.minecraft.item.Item;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class BrefkStageItemInit {

    public static final DeferredRegister<Item> BREFK = DeferredRegister.create(ForgeRegistries.ITEMS, Ervin_mod_1.MOD_ID);

    public static final RegistryObject<Item> BREFK_STAGE0 = BREFK.register("brefk/brefk_stage0", () -> new Item((new Item.Properties()).food(Foods.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE1 = BREFK.register("brefk/brefk_stage1", () -> new BrefkStage1((new Item.Properties()).containerItem(BREFK_STAGE0.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE2 = BREFK.register("brefk/brefk_stage2", () -> new BrefkStage2((new Item.Properties()).containerItem(BREFK_STAGE1.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE3 = BREFK.register("brefk/brefk_stage3", () -> new BrefkStage3((new Item.Properties()).containerItem(BREFK_STAGE2.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE4 = BREFK.register("brefk/brefk_stage4", () -> new BrefkStage4((new Item.Properties()).containerItem(BREFK_STAGE3.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE5 = BREFK.register("brefk/brefk_stage5", () -> new BrefkStage5((new Item.Properties()).containerItem(BREFK_STAGE4.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE6 = BREFK.register("brefk/brefk_stage6", () -> new BrefkStage6((new Item.Properties()).containerItem(BREFK_STAGE5.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE7 = BREFK.register("brefk/brefk_stage7", () -> new BrefkStage7((new Item.Properties()).containerItem(BREFK_STAGE6.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE8 = BREFK.register("brefk/brefk_stage8", () -> new BrefkStage8((new Item.Properties()).containerItem(BREFK_STAGE7.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE9 = BREFK.register("brefk/brefk_stage9", () -> new BrefkStage9((new Item.Properties()).containerItem(BREFK_STAGE8.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE10 = BREFK.register("brefk/brefk_stage10", () -> new BrefkStage10((new Item.Properties()).containerItem(BREFK_STAGE9.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE11 = BREFK.register("brefk/brefk_stage11", () -> new BrefkStage11((new Item.Properties()).containerItem(BREFK_STAGE10.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE12 = BREFK.register("brefk/brefk_stage12", () -> new BrefkStage12((new Item.Properties()).containerItem(BREFK_STAGE11.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE13 = BREFK.register("brefk/brefk_stage13", () -> new BrefkStage13((new Item.Properties()).containerItem(BREFK_STAGE12.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE14 = BREFK.register("brefk/brefk_stage14", () -> new BrefkStage14((new Item.Properties()).containerItem(BREFK_STAGE13.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE15 = BREFK.register("brefk/brefk_stage15", () -> new BrefkStage15((new Item.Properties()).containerItem(BREFK_STAGE14.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE16 = BREFK.register("brefk/brefk_stage16", () -> new BrefkStage16((new Item.Properties()).containerItem(BREFK_STAGE15.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE17 = BREFK.register("brefk/brefk_stage17", () -> new BrefkStage17((new Item.Properties()).containerItem(BREFK_STAGE16.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE18 = BREFK.register("brefk/brefk_stage18", () -> new BrefkStage18((new Item.Properties()).containerItem(BREFK_STAGE17.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE19 = BREFK.register("brefk/brefk_stage19", () -> new BrefkStage19((new Item.Properties()).containerItem(BREFK_STAGE18.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE20 = BREFK.register("brefk/brefk_stage20", () -> new BrefkStage20((new Item.Properties()).containerItem(BREFK_STAGE19.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE21 = BREFK.register("brefk/brefk_stage21", () -> new BrefkStage21((new Item.Properties()).containerItem(BREFK_STAGE20.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE22 = BREFK.register("brefk/brefk_stage22", () -> new BrefkStage22((new Item.Properties()).containerItem(BREFK_STAGE21.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE23 = BREFK.register("brefk/brefk_stage23", () -> new BrefkStage23((new Item.Properties()).containerItem(BREFK_STAGE22.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE24 = BREFK.register("brefk/brefk_stage24", () -> new BrefkStage24((new Item.Properties()).containerItem(BREFK_STAGE23.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE25 = BREFK.register("brefk/brefk_stage25", () -> new BrefkStage25((new Item.Properties()).containerItem(BREFK_STAGE24.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE26 = BREFK.register("brefk/brefk_stage26", () -> new BrefkStage26((new Item.Properties()).containerItem(BREFK_STAGE25.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE27 = BREFK.register("brefk/brefk_stage27", () -> new BrefkStage27((new Item.Properties()).containerItem(BREFK_STAGE26.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE28 = BREFK.register("brefk/brefk_stage28", () -> new BrefkStage28((new Item.Properties()).containerItem(BREFK_STAGE27.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE29 = BREFK.register("brefk/brefk_stage29", () -> new BrefkStage29((new Item.Properties()).containerItem(BREFK_STAGE28.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE30 = BREFK.register("brefk/brefk_stage30", () -> new BrefkStage30((new Item.Properties()).containerItem(BREFK_STAGE29.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE31 = BREFK.register("brefk/brefk_stage31", () -> new BrefkStage31((new Item.Properties()).containerItem(BREFK_STAGE30.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE32 = BREFK.register("brefk/brefk_stage32", () -> new BrefkStage32((new Item.Properties()).containerItem(BREFK_STAGE31.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE33 = BREFK.register("brefk/brefk_stage33", () -> new BrefkStage33((new Item.Properties()).containerItem(BREFK_STAGE32.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE34 = BREFK.register("brefk/brefk_stage34", () -> new BrefkStage34((new Item.Properties()).containerItem(BREFK_STAGE33.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE35 = BREFK.register("brefk/brefk_stage35", () -> new BrefkStage35((new Item.Properties()).containerItem(BREFK_STAGE34.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE36 = BREFK.register("brefk/brefk_stage36", () -> new BrefkStage36((new Item.Properties()).containerItem(BREFK_STAGE35.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE37 = BREFK.register("brefk/brefk_stage37", () -> new BrefkStage37((new Item.Properties()).containerItem(BREFK_STAGE36.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE38 = BREFK.register("brefk/brefk_stage38", () -> new BrefkStage38((new Item.Properties()).containerItem(BREFK_STAGE37.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE39 = BREFK.register("brefk/brefk_stage39", () -> new BrefkStage39((new Item.Properties()).containerItem(BREFK_STAGE38.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE40 = BREFK.register("brefk/brefk_stage40", () -> new BrefkStage40((new Item.Properties()).containerItem(BREFK_STAGE39.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE41 = BREFK.register("brefk/brefk_stage41", () -> new BrefkStage41((new Item.Properties()).containerItem(BREFK_STAGE40.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE42 = BREFK.register("brefk/brefk_stage42", () -> new BrefkStage42((new Item.Properties()).containerItem(BREFK_STAGE41.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE43 = BREFK.register("brefk/brefk_stage43", () -> new BrefkStage43((new Item.Properties()).containerItem(BREFK_STAGE42.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE44 = BREFK.register("brefk/brefk_stage44", () -> new BrefkStage44((new Item.Properties()).containerItem(BREFK_STAGE43.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE45 = BREFK.register("brefk/brefk_stage45", () -> new BrefkStage45((new Item.Properties()).containerItem(BREFK_STAGE44.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE46 = BREFK.register("brefk/brefk_stage46", () -> new BrefkStage46((new Item.Properties()).containerItem(BREFK_STAGE45.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE47 = BREFK.register("brefk/brefk_stage47", () -> new BrefkStage47((new Item.Properties()).containerItem(BREFK_STAGE46.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE48 = BREFK.register("brefk/brefk_stage48", () -> new BrefkStage48((new Item.Properties()).containerItem(BREFK_STAGE47.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE49 = BREFK.register("brefk/brefk_stage49", () -> new BrefkStage49((new Item.Properties()).containerItem(BREFK_STAGE48.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE50 = BREFK.register("brefk/brefk_stage50", () -> new BrefkStage50((new Item.Properties()).containerItem(BREFK_STAGE49.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE51 = BREFK.register("brefk/brefk_stage51", () -> new BrefkStage51((new Item.Properties()).containerItem(BREFK_STAGE50.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE52 = BREFK.register("brefk/brefk_stage52", () -> new BrefkStage52((new Item.Properties()).containerItem(BREFK_STAGE51.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE53 = BREFK.register("brefk/brefk_stage53", () -> new BrefkStage53((new Item.Properties()).containerItem(BREFK_STAGE52.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE54 = BREFK.register("brefk/brefk_stage54", () -> new BrefkStage54((new Item.Properties()).containerItem(BREFK_STAGE53.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE55 = BREFK.register("brefk/brefk_stage55", () -> new BrefkStage55((new Item.Properties()).containerItem(BREFK_STAGE54.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE56 = BREFK.register("brefk/brefk_stage56", () -> new BrefkStage56((new Item.Properties()).containerItem(BREFK_STAGE55.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE57 = BREFK.register("brefk/brefk_stage57", () -> new BrefkStage57((new Item.Properties()).containerItem(BREFK_STAGE56.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE58 = BREFK.register("brefk/brefk_stage58", () -> new BrefkStage58((new Item.Properties()).containerItem(BREFK_STAGE57.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE59 = BREFK.register("brefk/brefk_stage59", () -> new BrefkStage59((new Item.Properties()).containerItem(BREFK_STAGE58.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE60 = BREFK.register("brefk/brefk_stage60", () -> new BrefkStage60((new Item.Properties()).containerItem(BREFK_STAGE59.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE61 = BREFK.register("brefk/brefk_stage61", () -> new BrefkStage61((new Item.Properties()).containerItem(BREFK_STAGE60.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE62 = BREFK.register("brefk/brefk_stage62", () -> new BrefkStage62((new Item.Properties()).containerItem(BREFK_STAGE61.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE63 = BREFK.register("brefk/brefk_stage63", () -> new BrefkStage63((new Item.Properties()).containerItem(BREFK_STAGE62.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE64 = BREFK.register("brefk/brefk_stage64", () -> new BrefkStage64((new Item.Properties()).containerItem(BREFK_STAGE63.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE65 = BREFK.register("brefk/brefk_stage65", () -> new BrefkStage65((new Item.Properties()).containerItem(BREFK_STAGE64.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE66 = BREFK.register("brefk/brefk_stage66", () -> new BrefkStage66((new Item.Properties()).containerItem(BREFK_STAGE65.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE67 = BREFK.register("brefk/brefk_stage67", () -> new BrefkStage67((new Item.Properties()).containerItem(BREFK_STAGE66.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE68 = BREFK.register("brefk/brefk_stage68", () -> new BrefkStage68((new Item.Properties()).containerItem(BREFK_STAGE67.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE69 = BREFK.register("brefk/brefk_stage69", () -> new BrefkStage69((new Item.Properties()).containerItem(BREFK_STAGE68.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE70 = BREFK.register("brefk/brefk_stage70", () -> new BrefkStage70((new Item.Properties()).containerItem(BREFK_STAGE69.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE71 = BREFK.register("brefk/brefk_stage71", () -> new BrefkStage71((new Item.Properties()).containerItem(BREFK_STAGE70.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE72 = BREFK.register("brefk/brefk_stage72", () -> new BrefkStage72((new Item.Properties()).containerItem(BREFK_STAGE71.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE73 = BREFK.register("brefk/brefk_stage73", () -> new BrefkStage73((new Item.Properties()).containerItem(BREFK_STAGE72.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE74 = BREFK.register("brefk/brefk_stage74", () -> new BrefkStage74((new Item.Properties()).containerItem(BREFK_STAGE73.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE75 = BREFK.register("brefk/brefk_stage75", () -> new BrefkStage75((new Item.Properties()).containerItem(BREFK_STAGE74.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE76 = BREFK.register("brefk/brefk_stage76", () -> new BrefkStage76((new Item.Properties()).containerItem(BREFK_STAGE75.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE77 = BREFK.register("brefk/brefk_stage77", () -> new BrefkStage77((new Item.Properties()).containerItem(BREFK_STAGE76.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE78 = BREFK.register("brefk/brefk_stage78", () -> new BrefkStage78((new Item.Properties()).containerItem(BREFK_STAGE77.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE79 = BREFK.register("brefk/brefk_stage79", () -> new BrefkStage79((new Item.Properties()).containerItem(BREFK_STAGE78.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE80 = BREFK.register("brefk/brefk_stage80", () -> new BrefkStage80((new Item.Properties()).containerItem(BREFK_STAGE79.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE81 = BREFK.register("brefk/brefk_stage81", () -> new BrefkStage81((new Item.Properties()).containerItem(BREFK_STAGE80.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE82 = BREFK.register("brefk/brefk_stage82", () -> new BrefkStage82((new Item.Properties()).containerItem(BREFK_STAGE81.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE83 = BREFK.register("brefk/brefk_stage83", () -> new BrefkStage83((new Item.Properties()).containerItem(BREFK_STAGE82.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE84 = BREFK.register("brefk/brefk_stage84", () -> new BrefkStage84((new Item.Properties()).containerItem(BREFK_STAGE83.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE85 = BREFK.register("brefk/brefk_stage85", () -> new BrefkStage85((new Item.Properties()).containerItem(BREFK_STAGE84.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE86 = BREFK.register("brefk/brefk_stage86", () -> new BrefkStage86((new Item.Properties()).containerItem(BREFK_STAGE85.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE87 = BREFK.register("brefk/brefk_stage87", () -> new BrefkStage87((new Item.Properties()).containerItem(BREFK_STAGE86.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE88 = BREFK.register("brefk/brefk_stage88", () -> new BrefkStage88((new Item.Properties()).containerItem(BREFK_STAGE87.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE89 = BREFK.register("brefk/brefk_stage89", () -> new BrefkStage89((new Item.Properties()).containerItem(BREFK_STAGE88.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE90 = BREFK.register("brefk/brefk_stage90", () -> new BrefkStage90((new Item.Properties()).containerItem(BREFK_STAGE89.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE91 = BREFK.register("brefk/brefk_stage91", () -> new BrefkStage91((new Item.Properties()).containerItem(BREFK_STAGE90.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE92 = BREFK.register("brefk/brefk_stage92", () -> new BrefkStage2((new Item.Properties()).containerItem(BREFK_STAGE91.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE93 = BREFK.register("brefk/brefk_stage93", () -> new BrefkStage3((new Item.Properties()).containerItem(BREFK_STAGE92.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE94 = BREFK.register("brefk/brefk_stage94", () -> new BrefkStage4((new Item.Properties()).containerItem(BREFK_STAGE93.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE95 = BREFK.register("brefk/brefk_stage95", () -> new BrefkStage5((new Item.Properties()).containerItem(BREFK_STAGE94.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE96 = BREFK.register("brefk/brefk_stage96", () -> new BrefkStage6((new Item.Properties()).containerItem(BREFK_STAGE95.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE97 = BREFK.register("brefk/brefk_stage97", () -> new BrefkStage7((new Item.Properties()).containerItem(BREFK_STAGE96.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE98 = BREFK.register("brefk/brefk_stage98", () -> new BrefkStage8((new Item.Properties()).containerItem(BREFK_STAGE97.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE99 = BREFK.register("brefk/brefk_stage99", () -> new BrefkStage9((new Item.Properties()).containerItem(BREFK_STAGE98.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE100 = BREFK.register("brefk/brefk_stage100", () -> new BrefkStage10((new Item.Properties()).containerItem(BREFK_STAGE99.get()).food(Foods.BREFK).group(ItemGroup.BREFK)));
    public static final RegistryObject<Item> BREFK_STAGE255 = BREFK.register("brefk/brefk_stage255", () -> new Item((new Item.Properties()).containerItem(BREFK_STAGE100.get()).food(Foods.BREFK)));
}
