package com.babcsany.minecraft.ervin_mod_1.init.item.tool.stone;

import com.babcsany.minecraft.ervin_mod_1.Ervin_mod_1;
import com.babcsany.minecraft.ervin_mod_1.item.ModItemTier;
import net.minecraft.item.*;
import net.minecraftforge.fml.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;

public class ToolItemInit {

    public static final DeferredRegister<Item> TOOL_ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Ervin_mod_1.MOD_ID);

    public static final RegistryObject<Item> BLACK_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/black_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> BLACK_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/black_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BLACK_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/black_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> BLACK_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/black_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BLACK_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/black_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> BLUE_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/blue_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> BLUE_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/blue_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BLUE_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/blue_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> BLUE_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/blue_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BLUE_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/blue_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> BROWN_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/brown_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> BROWN_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/brown_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BROWN_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/brown_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> BROWN_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/brown_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> BROWN_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/brown_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> CYAN_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/cyan_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> CYAN_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/cyan_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> CYAN_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/cyan_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> CYAN_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/cyan_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> CYAN_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/cyan_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> GREEN_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/green_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> GREEN_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/green_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> GREEN_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/green_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> GREEN_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/green_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> GREEN_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/green_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/light_blue_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/light_blue_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/light_blue_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/light_blue_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/light_blue_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE1_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/light_blue1_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE1_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/light_blue1_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE1_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/light_blue1_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE1_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/light_blue1_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_BLUE1_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/light_blue1_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_GRAY_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/light_gray_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_GRAY_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/light_gray_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_GRAY_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/light_gray_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_GRAY_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/light_gray_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIGHT_GRAY_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/light_gray_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> LIME_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/lime_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> LIME_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/lime_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIME_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/lime_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> LIME_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/lime_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> LIME_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/lime_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> MAGENTA_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/magenta_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> MAGENTA_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/magenta_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> MAGENTA_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/magenta_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> MAGENTA_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/magenta_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> MAGENTA_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/magenta_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/orange_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/orange_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/orange_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/orange_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> ORANGE_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/orange_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> PINK_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/pink_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> PINK_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/pink_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> PINK_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/pink_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> PINK_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/pink_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> PINK_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/pink_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/purple_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/purple_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/purple_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/purple_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> PURPLE_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/purple_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> RED_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/red_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> RED_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/red_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> RED_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/red_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> RED_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/red_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> RED_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/red_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> WHITE_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/white_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> WHITE_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/white_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> WHITE_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/white_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> WHITE_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/white_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> WHITE_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/white_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_STONE_AXE = TOOL_ITEMS.register("tools/stone/axe/yellow_stone_axe", () -> new AxeItem(ItemTier.STONE, 7.0F, -3.2F, (new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_STONE_HOE = TOOL_ITEMS.register("tools/stone/hoe/yellow_stone_hoe", () -> new HoeItem(ItemTier.STONE, -1, -2.0F, (new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_STONE_PICKAXE = TOOL_ITEMS.register("tools/stone/pickaxe/yellow_stone_pickaxe", () -> new PickaxeItem(ItemTier.STONE, 1, -2.8F, (new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_STONE_SHOVEL = TOOL_ITEMS.register("tools/stone/shovel/yellow_stone_shovel", () -> new ShovelItem(ItemTier.STONE,1.5F, -3.0F, (new Item.Properties())));
    public static final RegistryObject<Item> YELLOW_STONE_SWORD = TOOL_ITEMS.register("tools/stone/sword/yellow_stone_sword", () -> new SwordItem(ItemTier.STONE, 3, -2.4F, (new Item.Properties())));
}
